### ISSUE TITLE
receive default values as object

### ISSUE THREAD

**Issue by jhta** [jhta/form-autofill-js#2]
the idea is receive a object like:
````javascript
{
  name: 'Frank',
  last_purchased: 'June 23, 2018',
  institution: 'University of Arizona'
}

and fill the inputs with these `names`

**Comment by jhta** [comment]
not exactly, probably we can set some specific parameters with specific data by default

**Comment by galczo5** [comment]
I'm not sure if I undestand you, but I'll try to do it today.

**Comment by jhta** [comment]
okay :)

**Comment by galczo5** [comment]
Do you want me to put "missing" semicolons too? I know that it's not necessary in js. What is your opinion about it?

**Comment by galczo5** [comment]
https://github.com/jhta/form-autofill-js/pull/7

**Comment by galczo5** [comment]
Any posibility to end this issue soon?

**Comment by jhta** [comment]
thanks for the PR :)
